### PR TITLE
Self Joining address considers enable-ssl setting 

### LINKED ISSUE #102: Enable SSL needs management
We are using this project as the lighthouse seed node for our Akka Cluster. As we moved on to use SSL encrypted communication we found that `enable-ssl=true` causes an issue in the lighthouse project startup.
The self address of the lighthouse is using `akka.tcp` as the protocol. So when the lighthouse node which is configured to use `ssl` will fail to join itself as the self address will be `akka.tcp://webcrawler@lighthouse1:4053]`.

The self address should consider if protocol is ssl encrypted or not.

### PR DESCRIPTION
**Pull request by JinsPeter**
Fixes #102

### CODE REVIEW

**Comment by JinsPeter** [comment]
@Aaronontheweb When can I expect this change to make it into the docker registry release.

**Comment by Aaronontheweb** [comment]
@JinsPeter I think we need you to sign the CLA first

https://github.com/petabridge/lighthouse/pull/103#issuecomment-551029332 - mostly a formality.

But otherwise, once I've had a chance to test things locally it should be good to go. You're going to need to pass in some SSL certificate settings inside the Docker container in order for this to be effective, however - isn't that going to be an issue without creating your own image on top of ours?

**Comment by JinsPeter** [comment]
@Aaronontheweb  I have already signed the agreement, But I don't understand why the status is not getting refletcted here. I clicked recheck button many times after signing the CLA as well. 
image

An interesting thing I noticed is that when I check on this PR each new day, the agreement can be signed again. Signed today as well. Then, for that day it will show as already signed when I navigate the license signing page. Not reflecting in the PR.

**Comment by JinsPeter** [comment]
@Aaronontheweb About passing in the certificate. That being a hocon setting, the user of the lighthouse can do this when configuring.
I tested this change locally without dockers. Our DevOps person is confident to get the certificate part working with a docker too.

**Comment by JinsPeter** [comment]
@Aaronontheweb  Ignore my previous comment about CLI being signed. The email I had configured in the my local git was not linked to this account. Got that rectified and now the CLA Signed status has been updated. :)

**Comment by Aaronontheweb** [comment]
Thanks @JinsPeter - we'll do a new release soon. Going to get https://github.com/petabridge/lighthouse/issues/104 closed out and then we'll push one.

**Pull request merged**
