### PR TITLE
Using Wire Serializer With Lighthouse

### PR DESCRIPTION
**Pull request by contactsamie**
Added Akka wire Serialization package and updated configurations . Pulling from the lattest base
Tried against the https://github.com/contactsamie/AkkaBootCamp-FamilyCluster , looks good

### CODE REVIEW

**Comment by contactsamie** [comment]
#17

**Comment by contactsamie** [comment]
Coming from #17

**Comment by Caldas** [comment]
@contactsamie are you going to finish it??

**Comment by contactsamie** [comment]
@Caldas this pull is a new one, and good to go. I closed the previous one

**Comment by contactsamie** [comment]
Closing because latest akka favors Hyperion serialization

**Pull request closed without merging**
